image: node:latest

cache:
  paths:
   - node_modules/

before_script:
  - yarn install

stages:
  - build_deploy

build_&_deploy_app:
  stage: build_deploy
  only:
   - master
  script:
   - CLIENT_ID=${CLIENT_ID} CLIENT_SECRET=${CLIENT_SECRET} REFRESH_TOKEN=${REFRESH_TOKEN} node_modules/gulp/bin/gulp.js release