image: node:latest

cache:
  paths:
   - node_modules/

before_script:
  - yarn install

stages:
  - build_deploy

build_&_deploy_app:
  stage: build_deploy
  only:
   - master
  script:
   - gulp release